my_set={1,2,3,4,3,2}
print(my_set)
my_set=set([1,2,3,2])
print(my_set)
#my_set={1,2,[3,4]}
my_set.add(2)
print(my_set)
my_set.update([2,3,4])
print(my_set)
########################
#discard,remove
my_set={1,3,4,5,6}
print(my_set)
my_set.discard(4)
print(my_set)
my_set.remove(6)
print(my_set)
my_set={1,3,4,5,6}
print(my_set.pop())
print(my_set.pop())
